// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msbmyiqhohtjdfbjmxlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zYm15aXFob2h0amRmYmpteGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDk2MzIsImV4cCI6MjA2OTk4NTYzMn0.TkCDTkST4CNAEvMOC08GI7jvS0mlJ5hhMsKxw7heDak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Security: Disable sensitive console logs in production
if (typeof window !== 'undefined' && window.location.hostname !== 'localhost') {
  const originalLog = console.log;
  const originalError = console.error;
  const originalWarn = console.warn;
  
  const sensitiveKeywords = ['supabase', 'database', 'query', 'rpc', 'session', 'auth', 'token', 'api', 'key', 'secret'];
  
  const filterLogs = (originalFn: Function) => (...args: any[]) => {
    const hasKeyword = args.some(arg => {
      if (typeof arg === 'string') {
        return sensitiveKeywords.some(keyword => 
          arg.toLowerCase().includes(keyword)
        );
      }
      if (typeof arg === 'object' && arg !== null) {
        const stringified = JSON.stringify(arg).toLowerCase();
        return sensitiveKeywords.some(keyword => stringified.includes(keyword));
      }
      return false;
    });
    
    if (!hasKeyword) {
      originalFn.apply(console, args);
    }
  };
  
  console.log = filterLogs(originalLog);
  console.error = filterLogs(originalError); 
  console.warn = filterLogs(originalWarn);
}