// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msbmyiqhohtjdfbjmxlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zYm15aXFob2h0amRmYmpteGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDk2MzIsImV4cCI6MjA2OTk4NTYzMn0.TkCDTkST4CNAEvMOC08GI7jvS0mlJ5hhMsKxw7heDak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'tone2vibe-app'
    }
  }
});

// Disable console logging in production
if (import.meta.env.PROD) {
  const originalLog = console.log;
  const originalError = console.error;
  const originalWarn = console.warn;
  
  const sensitiveKeywords = ['supabase', 'database', 'query', 'rpc', 'session', 'auth', 'token', 'api_key'];
  
  console.log = (...args: any[]) => {
    const hasKeyword = args.some(arg => 
      typeof arg === 'string' && sensitiveKeywords.some(keyword => 
        arg.toLowerCase().includes(keyword)
      )
    );
    if (!hasKeyword) originalLog.apply(console, args);
  };
  
  console.error = (...args: any[]) => {
    const hasKeyword = args.some(arg => 
      typeof arg === 'string' && sensitiveKeywords.some(keyword => 
        arg.toLowerCase().includes(keyword)
      )
    );
    if (!hasKeyword) originalError.apply(console, args);
  };
  
  console.warn = (...args: any[]) => {
    const hasKeyword = args.some(arg => 
      typeof arg === 'string' && sensitiveKeywords.some(keyword => 
        arg.toLowerCase().includes(keyword)
      )
    );
    if (!hasKeyword) originalWarn.apply(console, args);
  };
}